apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s 
    
    scrape_configs:
      - job_name: 'kubernetes-service-endpoints'
      #serviceDicovery
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_scrape_me]
            regex: true
            action: keep
          - source_labels: [__meta_kubernetes_service_name]
            regex: (.*)
            target_label: job_name
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: web
            target_label: __metrics_path__
            replacement: /metrics